# version: '3.8'
services:

  passinapp:
    image: ericksvasc/passin:1.0.0
    # build: .
    ports:
      - 4173:4173
    environment:
      VITE_APP_DATABASE_URL: ${VITE_APP_DATABASE_URL}
    env_file:
      - .env
    # networks:
    #   - serverapi

# networks:
#   serverapi:
#     external: 

